config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      get 'search'
    end
  end
  
  root 'posts#index'

end

app/models/anchor.rb
class Anchor < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :images
  
  scope :min_price, -> (min) { where("price > ?", min) }
  scope :max_price, -> (max) { where("price < ?", max) }
  scope :bedrooms, -> (bedrooms) { where bedrooms: bedrooms}
  scope :bathrooms, -> (bathrooms) { where bathrooms: bathrooms}
  scope :neighborhood, -> (neighborhood) { where neighborhood: neighborhood}
  scope :cats, -> (cats) { where cats: cats}
  scope :dogs, -> (dogs) { where dogs: dogs}
  scope :min_sqft, -> (min) { where("sqft > ?", min) }
  scope :max_sqft, -> (max) { where("sqft < ?", max) }
  scope :w_d_in_unit, -> (w_d_in_unit) { where w_d_in_unit: w_d_in_unit}
  scope :street_parking, -> (street_parking) { where street_parking: street_parking}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :remove_blank_params, only: [:search]

  def search    
    @posts = Post.order("timestamp DESC")
    @posts = @posts.min_price(params[:min_price]) if params[:min_price].present?
    @posts = @posts.max_price(params[:max_price]) if params[:max_price].present?
    @posts = @posts.bedrooms(params[:bedrooms]) if params[:bedrooms].present?
    @posts = @posts.bathrooms(params[:bathrooms]) if params[:bathrooms].present?
    @posts = @posts.neighborhood(params[:neighborhood]) if params[:neighborhood].present?
    @posts = @posts.cats(params[:cats]) if params[:cats].present?
    @posts = @posts.dogs(params[:dogs]) if params[:dogs].present?
    @posts = @posts.min_sqft(params[:min_sqft]) if params[:min_sqft].present?
    @posts = @posts.max_sqft(params[:max_sqft]) if params[:max_sqft].present?
    @posts = @posts.w_d_in_unit(params[:w_d_in_unit]) if params[:w_d_in_unit].present?
    @posts = @posts.street_parking(params[:street_parking]) if params[:street_parking].present?
    
    @posts = @posts.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /posts
  # GET /posts.json
  def index
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @images = @post.images
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
    
    def remove_blank_params
      
      check = false      
      params.map { |name, value| check = true if value == "" }
  
      params.reject! { |name, value| value == "" }
      
      puts params.to_query
  
      if check == true
        redirect_to search_posts_path(params)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:min_price, :max_price, :bedrooms, :bathrooms, :cats, :dogs, :min_sqft, :max_sqft, :w_d_in_unit, :street_parking)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Padlistings2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :heading %><br>
    <%= f.text_field :heading %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="center">
      <h1>Craigslist Scraper</h1>
      <h2>The easiest way to find apartment rentals in Brooklyn</h2>
    </div>
    <div class="filter">

    <%= form_tag search_posts_path, method: :get, class: "form-inline" do %>
      
        <div class="row">
          <div class="col-md-4">
            <%= label_tag "Price" %>
          </div>
          <div class="col-md-2">
            <%= label_tag :bedrooms %>
          </div>
          <div class="col-md-2">
            <%= label_tag :bathrooms %>
          </div>
          <div class="col-md-4">
            <%= label_tag :neighborhood %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <%= text_field_tag :min_price, params[:min_price], placeholder: "minimum", class: "form-control input-sm" %>
            <%= text_field_tag :max_price, params[:max_price], placeholder: "maximum", class: "form-control input-sm" %>
          </div>

          <div class="form-group col-md-2">
            <%= text_field_tag :bedrooms, params[:bedrooms], size: "10", placeholder: "# of rooms", class: "form-control input-sm" %>
          </div>  
          <div class="form-group col-md-2">
            <%= text_field_tag :bathrooms, params[:bathrooms], size: "10", placeholder: "# of baths", class: "form-control input-sm" %>
          </div>
          
          <div class="col-md-4">
            <%= select_tag(:neighborhood, options_from_collection_for_select(Location.all, :name, :name, params[:neighborhood]), 
                { include_blank: true, class: "form-control input-sm" }) %>
          </div>
        </div>
        
        <br>

        <div class="row">
          <div class="col-md-4">
            <%= label_tag "SqFt" %>
          </div>
        </div>

        <div class="row">
          <div class="form-group col-md-4">
            <%= text_field_tag :min_sqft, params[:min_sqft], placeholder: "minimum", class: "form-control input-sm" %>
            <%= text_field_tag :max_sqft, params[:max_sqft], placeholder: "maximum", class: "form-control input-sm" %>
          </div>

          <div class="form-group col-md-1">
            <%= label_tag :cats %>
            <%= check_box_tag :cats, "YES", params[:cats].present? %>
          </div>
          
          <div class="form-group col-md-1">
            <%= label_tag :dogs %>
            <%= check_box_tag :dogs, "YES", params[:dogs].present? %>
          </div>
          <div class="form-group col-md-2">
            <%= label_tag :w_d_in_unit %>
            <%= check_box_tag :w_d_in_unit, "YES", params[:w_d_in_unit].present? %>
          </div>
          
          <div class="form-group col-md-2">
            <%= label_tag :street_parking %>
            <%= check_box_tag :street_parking, "YES", params[:street_parking].present? %>
          </div>

          <div class="form-group">
            <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
          </div>

        </div>
              
        <br>

      <% end %>

  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<div class="container">
  <div class="filter">

    <%= form_tag search_posts_path, method: :get, class: "form-inline" do %>
      
      <div class="row">
        <div class="col-md-4">
          <%= label_tag "Price" %>
        </div>
        <div class="col-md-2">
          <%= label_tag :bedrooms %>
        </div>
        <div class="col-md-2">
          <%= label_tag :bathrooms %>
        </div>
        <div class="col-md-4">
          <%= label_tag :neighborhood %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <%= text_field_tag :min_price, params[:min_price], placeholder: "minimum", class: "form-control input-sm" %>
          <%= text_field_tag :max_price, params[:max_price], placeholder: "maximum", class: "form-control input-sm" %>
        </div>

        <div class="form-group col-md-2">
          <%= text_field_tag :bedrooms, params[:bedrooms], size: "10", class: "form-control input-sm" %>
        </div>  
        <div class="form-group col-md-2">
          <%= text_field_tag :bathrooms, params[:bathrooms], size: "10", class: "form-control input-sm" %>
        </div>
        
        <div class="col-md-4">
          <%= select_tag(:neighborhood, options_from_collection_for_select(Location.all, :name, :name, params[:neighborhood]), 
              { include_blank: true, class: "form-control input-sm" }) %>
        </div>
      </div>
      
      <br>

      <div class="row">
        <div class="col-md-4">
          <%= label_tag "SqFt" %>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-md-4">
          <%= text_field_tag :min_sqft, params[:min_sqft], placeholder: "minimum", class: "form-control input-sm" %>
          <%= text_field_tag :max_sqft, params[:max_sqft], placeholder: "maximum", class: "form-control input-sm" %>
        </div>

        <div class="form-group col-md-1">
          <%= label_tag :cats %>
          <%= check_box_tag :cats, "YES", params[:cats].present? %>
        </div>
        
        <div class="form-group col-md-1">
          <%= label_tag :dogs %>
          <%= check_box_tag :dogs, "YES", params[:dogs].present? %>
        </div>
        <div class="form-group col-md-2">
          <%= label_tag :w_d_in_unit %>
          <%= check_box_tag :w_d_in_unit, "YES", params[:w_d_in_unit].present? %>
        </div>
        
        <div class="form-group col-md-2">
          <%= label_tag :street_parking %>
          <%= check_box_tag :street_parking, "YES", params[:street_parking].present? %>
        </div>

        <div class="form-group">
          <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
        </div>

      </div>
            
      <br>

    <% end %>
  </div>
  
  <br>

  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th class="center">Picture</th>
        <th class="center">Heading</th>
        <th class="center">Neighborhood</th>
        <th class="center">Beds</th>
        <th class="center">Baths</th>
        <th class="center">Price</th>
        <th class="center">Last Updated</th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td width="13%" height="120px">            
            <%= link_to post_path(post) do %>
              <% if post.images.empty? %>
                <%= image_tag "http://www.eastbaymodern.com/idx/img/no-image.gif", class: "thumbnail" %>
              <% else %>
                <%= image_tag post.images.first.url, class: "thumbnail" %>
              <% end %>
            <% end %>
          </td>
          <td style="vertical-align:middle" width="45%"><%= post.heading %></td>
          <td class="center" style="vertical-align:middle"><%= post.neighborhood %></td>
          <td class="center" style="vertical-align:middle"><%= post.bedrooms %></td>
          <td class="center" style="vertical-align:middle"><%= post.bathrooms %></td>
          <td class="center" style="vertical-align:middle"><%= number_to_currency(post.price, precision: 0) %></td>
          <td class="center" style="vertical-align:middle"><%= "#{time_ago_in_words(Time.at(post.timestamp.to_i))} ago" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/posts/show.html.erb
<section class="listing">
  <div class="container">
    <div class="header">
      <p id="notice"><%= notice %></p>
      <h4><%= @post.heading.html_safe %></h4>
      <p><%= link_to @post.external_url, @post.external_url %></p>
    </div>
    <div class="row">
      <div class="col-md-7">
        <% if @images.blank? %>
          <%= image_tag "http://www.eastbaymodern.com/idx/img/no-image.gif", class: "thumbnail" %>
        <% else %>
          <% @images.each do |image| %>
            <%= image_tag image.url, class: "thumbnail" %>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-5">
        <div class="basic_info">
          <h5>Basic Information</h5>
          <p><%= number_to_currency(@post.price, precision: 0) %></p>

          <p><%= "Last updated on #{Time.at(@post.timestamp.to_i).strftime("%m/%d/%y")}" %></p>
          
          <% if @post.neighborhood.present? %>
            <%= "Neighborhood: #{@post.neighborhood}" %><br>
          <% end %>

          <% if @post.bedrooms.present? %>
            <%= "Bedrooms: #{@post.bedrooms}" %><br>
          <% end %>
          
          <% if @post.bathrooms.present? %>
            <%= "Bathrooms: #{@post.bathrooms}" %><br>
          <% end %>
          
          <% if @post.cats.present? %>
            <%= "Cats allowed: #{@post.cats}" %><br>
          <% end %>
          
          <% if @post.dogs.present? %>
            <%= "Dogs allowed: #{@post.dogs}" %><br>
          <% end %>
          
          <% if @post.sqft.present? %>
            <%= "Square footage: #{@post.sqft}" %><br>
          <% end %>
          
          <% if @post.w_d_in_unit.present? %>
            <%= "Washer/dryer in unit: #{@post.w_d_in_unit} <br>" %><br>
          <% end %>
          
          <% if @post.street_parking.present? %>
            <%= "Street parking available: #{@post.street_parking}" %><br>
          <% end %>
          
        </div>
        
        <div class="description">
          <h5>Description</h5>
          <p><%= raw(@post.body) %></p>
        </div>
        
      </div>
    </div>
      
  </div>
</section>